# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:3.6.5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: bug_monitor
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: langke

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 28081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: langke